### ISSUE TITLE
Interpolation not evaluated from serverless.yaml

### ISSUE THREAD

**Issue by lukiffer** [rurri/serverless-resources-env#15]
This looks to be similar to #12 but I believe it's unique, and it may be working as intended, but the way our serverless.yml file is setup isn't working with the plugin:

We have environment-specific configuration values (e.g. AWS account number, region, etc.) in a separate `serverless.<stage>.yml` where <stage> is any of dev, stage, or prod.

In your main serverless.yml file, we're merging these into the config like:

```yaml
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.6
  region: ${file(./serverless.${self:provider.stage}.yml):DEFAULT_REGION}
```

It doesn't appear that the interpolation that serverless does is being evaluated when pulling the CloudFormation details after the deployment. The plugin exits with the following error:

```
Serverless: [serverless-resources-env] Looking up resources for CF Named: example-stack-dev

  Unknown Endpoint ---------------------------------------

  Inaccessible host: `cloudformation.'. This service may not be available in the `${file(./serverless.${self:provider.stage}.yml):DEFAULT_REGION}' region.
```
